### ISSUE TITLE
Build Home page

### ISSUE THREAD

**Issue by Aidenwebb** [RootwireLtd/design.rootwire.co.uk#2]
Using https://design.ubuntu.com/ as reference

Build a homepage with the following segments

* Our brand
* Design resources
* How to contribute

**Comment by KatBiel** [comment]
![Screenshot 2024-05-10 143801](https://github.com/RootwireLtd/design.rootwire.co.uk/assets/140555163/e033907c-8240-487f-9853-3b3ec048d897)

**Comment by KatBiel** [comment]
Page is completed, designed to look well on different device sizes.
